# Remove version as it's now obsolete
services:
  trae-app:    # Changed from 'web' to match the image name from GitHub Actions
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    command: npm run dev